export * from './TouchCpuComponentScrapper';
export * from './TouchVideoCardComponentScrapper';
export * from './TouchSsdComponentScrapper';
export * from './TouchHddComponentScrapper';
export * from './TouchCaseComponentScrapper';
export * from './TouchCoolerComponentScrapper';
export * from './TouchMemoryComponentScrapper';
export * from './TouchMotherboardComponentScrapper';
export * from './TouchPowerSupplyComponentScrapper';